version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[GitHub Action]"

  # e2eTests
  - package-ecosystem: gradle
    directory: "/e2eTests"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[e2eTests]"

  # buildSrc
  - package-ecosystem: gradle
    directory: "/buildSrc"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[Conventions]"

  # Libraries

  ## clearinghouse
  - package-ecosystem: gradle
    directory: "/lib/clearinghouse"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[Clearinghouse]"

  ## crypt4gh
  - package-ecosystem: gradle
    directory: "/lib/crypt4gh"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[Crypt4gh]"

  ## tsd-file-api-client
  - package-ecosystem: gradle
    directory: "/lib/tsd-file-api-client"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[TSD-File-API-Client]"

  # Services

  ## tsd-api-mock
  - package-ecosystem: gradle
    directory: "/services/tsd-api-mock"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[TSD-API-mock]"

  ## localega-tsd-proxy
  - package-ecosystem: gradle
    directory: "/services/localega-tsd-proxy"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[Localega-TSD-Proxy]"

  ## MQ-Interceptor
  - package-ecosystem: gomod
    directory: "/services/mq-interceptor"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[MQ-Interceptor]"

  ## CEGA-mock
  - package-ecosystem: gomod
    directory: "/services/cega-mock"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[CEGA-mock]"

  # CLI

  ## lega-commander
  - package-ecosystem: gomod
    directory: "/cli/lega-commander"
    groups:
      all-modules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "[Lega-Commander]"
