version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[GitHub Action]'

  - package-ecosystem: gradle
    directory: /e2eTests
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[e2eTests]'
  - package-ecosystem: docker
    directory: /e2eTests
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[e2eTests]'
  - package-ecosystem: docker-compose
    directory: /e2eTests
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[e2eTests]'

  - package-ecosystem: gradle
    directory: /buildSrc
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[Conventions]'

  - package-ecosystem: gradle
    directory: /lib/clearinghouse
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[Clearinghouse]'

  - package-ecosystem: gradle
    directory: /lib/crypt4gh
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[Crypt4gh]'

  - package-ecosystem: gradle
    directory: /lib/tsd-file-api-client
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[TSD-File-API-Client]'

  - package-ecosystem: gradle
    directory: /services/tsd-api-mock
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[TSD-API-mock]'
  - package-ecosystem: docker
    directory: /services/tsd-api-mock
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[TSD-API-mock]'

  - package-ecosystem: gradle
    directory: /services/localega-tsd-proxy
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[Localega-TSD-Proxy]'
  - package-ecosystem: docker
    directory: /services/localega-tsd-proxy
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[Localega-TSD-Proxy]'

  - package-ecosystem: gomod
    directory: /services/mq-interceptor
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[MQ-Interceptor]'
  - package-ecosystem: docker
    directory: /services/mq-interceptor
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[MQ-Interceptor]'

  - package-ecosystem: gomod
    directory: /services/cega-mock
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[CEGA-mock]'
  - package-ecosystem: docker
    directory: /services/cega-mock
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[CEGA-mock]'

  - package-ecosystem: gomod
    directory: /cli/lega-commander
    groups:
      all-modules:
        patterns:
          - '*'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Oslo
    commit-message:
      prefix: '[Lega-Commander]'